import { type NextPage } from "next";
import Head from "next/head";
import React, { type MouseEvent, useEffect, useState } from "react";

interface Books {
  id: number;
  bookTitle: string;
  bookAuthor: string;
  bookGenre: string;
}

const Home: NextPage = () => {
  const [data, setData] = useState<Books[]>();
  const [book, setBook] = useState({
    title: "",
    author: "",
    genre: "",
  });

  const getBooks = async () => {
    const books = await fetch("/api/books", {
      method: "GET",
      headers: {
        "Content-type": "application/json",
      },
    });
    setData(await books.json());
  };

  useEffect(() => {
    getBooks();
  }, []);

  const resetForm = () => {
    setBook({
      title: "",
      author: "",
      genre: "",
    });
  };

  const handleSubmit = (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    const { title, author, genre } = book;
    fetch("/api/books", {
      method: "POST",
      headers: {
        "Content-type": "application/json",
      },
      body: JSON.stringify({
        title: title,
        author: author,
        genre: genre,
      }),
    });
    resetForm();
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-4 flex h-full flex-col bg-gray-500 p-2">
        <div className="flex flex-grow flex-row items-center justify-evenly align-middle">
          <div className="flex flex-col">
            <div>
              <h3>Book Name</h3>
              <input
                onChange={(e) => setBook({ ...book, title: e.target.value })}
                value={book.title}
                type="text"
                name="book"
                id="book"
              />
            </div>
            <div>
              <h3>Author Name</h3>
              <input
                onChange={(e) => setBook({ ...book, author: e.target.value })}
                value={book.author}
                type="text"
                name="author"
                id="author"
              />
            </div>
            <div>
              <h3>Genre</h3>
              <input
                onChange={(e) => setBook({ ...book, genre: e.target.value })}
                value={book.genre}
                type="text"
                name="genre"
                id="genre"
              />
            </div>
          </div>
          <button
            onClick={handleSubmit}
            className="h-12 rounded-md bg-blue-400"
          >
            Add Book
          </button>
        </div>
        <div className="mx-auto mt-8 flex flex-row gap-8">
          {data?.map((e) => (
            <div
              className="flex flex-col border border-cyan-500 p-10"
              key={e.id}
            >
              <p>Title: {e.bookTitle}</p>
              <p>Author: {e.bookAuthor}</p>
              <p>Genre: {e.bookGenre}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
